name: Reusable build steps
description: Setups the build environment and builds Jameica and Hibiscus
runs:
  using: "composite"
  steps:
  - name: Set up JDK for x64
    uses: actions/setup-java@v5
    with:
      java-version: '17'
      distribution: 'temurin'
      architecture: x64
      cache: 'maven'

  - name: Restore build dependencies
    id: restore-cache
    uses: actions/cache@v4
    with:
      path: |
        jameica/bin/
        jameica/lib/
        jameica/releases/jameica-lib.jar
        hibiscus/bin/
        hibiscus/lib/
        hibiscus/releases/hibiscus-lib.jar
      key: ${{ hashFiles('jverein/build/build.properties', 'jverein/build/build.xml') }}

  - name: Build Jameica and Hibiscus
    if: steps.restore-cache.outputs.cache-hit != 'true'
    shell: bash
    run: ant -noinput -buildfile jverein/build/build.xml build-dependencies
