name: OpenJVerein build check

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'plugin.xml'
      - 'pom.xml'
      - 'lib/**'
      - 'src/**'
      - 'junit/**'
      - '.github/workflows/**/*.yml'
      - '.github/actions/**/*.yml'
  push:
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout openjverein
      uses: actions/checkout@v6
      with:
        path: jverein

    - name: Setup
      uses: ./jverein/.github/actions/build-dependencies

    - name: Build openjverein plugin
      run: mvn -B -f jverein/pom.xml test
