# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: OpenJVerein nightly release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout openjverein
      uses: actions/checkout@v6
      with:
        ref: 'master'
        path: jverein

    - name: Setup
      uses: ./jverein/.github/actions/build-dependencies

    - name: Build openjverein plugin
      id: openjverein
      run: |
        mvn -B -f jverein/pom.xml -Pnightly package

        tmp_base_version=$(mvn -q -f jverein/pom.xml help:evaluate -Dexpression=project.version -DforceStdout | tail -n1)
        tmp_version="${tmp_base_version}-nightly"
        tmp_filename="jverein.${tmp_base_version}-nightly.zip"
        tmp_path="target/releases/nightly/${tmp_filename}"

        echo "selected_version=${tmp_version}" >> $GITHUB_OUTPUT
        echo "selected_filename=${tmp_filename}" >> $GITHUB_OUTPUT
        echo "selected_path=${tmp_path}" >> $GITHUB_OUTPUT

        builddatetime=$(date +'%Y-%m-%d %H:%M')
        echo "### Version: ${tmp_version} | filename: ${tmp_filename} | build datetime: ${builddatetime}" >> $GITHUB_STEP_SUMMARY

    # Update tag
    - name: Tag repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: ${{ steps.openjverein.outputs.selected_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ steps.openjverein.outputs.selected_version }}
        prerelease: true
        name: Release ${{ steps.openjverein.outputs.selected_version }}
        files: ./jverein/${{ steps.openjverein.outputs.selected_path }}
        generate_release_notes: false
